buildscript {
    ext {
        springBootVersion = '2.7.8'
        javaVersion = '11'
    }
}

plugins {
    id 'org.springframework.boot' version '2.7.8' apply false
    id 'io.spring.dependency-management' version '1.0.11.RELEASE' apply false
}

allprojects {
    group = 'com.binaryho'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
}
